version: "3"

tasks:
  default:
    cmds:
      - task --list-all
  install:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
      - go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
      - go mod tidy
  syso:
    cmds:
      - rsrc -arch amd64 -ico ./assets/icon.ico -o rsrc_windows_amd64.syso
      - rsrc -arch 386 -ico ./assets/icon.ico -o rsrc_windows_386.syso
  build:
    cmds:
      - go build -o bin/prepare-media.exe .
    depends:
      - syso
  run:
    cmds:
      - bin/prepare-media.exe
    depends:
      - build
  test:
    cmds:
      - go test -v ./...
  lint:
    desc: Run linting
    cmds:
      - golangci-lint run -v
  fieldalignment:
    desc: Run fieldalignment.
    cmds:
      - fieldalignment -fix ./...
